// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOq8kVepeuhSOmvtQCiPmMLKnFSE4PnNQ',
    appId: '1:792800466297:web:cb87e5314a86247a908ba8',
    messagingSenderId: '792800466297',
    projectId: 'flutter-test-8d68a',
    authDomain: 'flutter-test-8d68a.firebaseapp.com',
    storageBucket: 'flutter-test-8d68a.firebasestorage.app',
    measurementId: 'G-9HM6TF4QDZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfTmDXmXkXhsQVEvTgianYIYlj5F80Rcg',
    appId: '1:792800466297:android:90e1b19670a20c58908ba8',
    messagingSenderId: '792800466297',
    projectId: 'flutter-test-8d68a',
    storageBucket: 'flutter-test-8d68a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNyPgb8-jRopesl0i7RHJyhnNoSo4ATxg',
    appId: '1:792800466297:ios:b23ff0981b9cb881908ba8',
    messagingSenderId: '792800466297',
    projectId: 'flutter-test-8d68a',
    storageBucket: 'flutter-test-8d68a.firebasestorage.app',
    iosBundleId: 'com.example.antMediaFlutterExample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNyPgb8-jRopesl0i7RHJyhnNoSo4ATxg',
    appId: '1:792800466297:ios:b23ff0981b9cb881908ba8',
    messagingSenderId: '792800466297',
    projectId: 'flutter-test-8d68a',
    storageBucket: 'flutter-test-8d68a.firebasestorage.app',
    iosBundleId: 'com.example.antMediaFlutterExample',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOq8kVepeuhSOmvtQCiPmMLKnFSE4PnNQ',
    appId: '1:792800466297:web:063c6f913e06fe24908ba8',
    messagingSenderId: '792800466297',
    projectId: 'flutter-test-8d68a',
    authDomain: 'flutter-test-8d68a.firebaseapp.com',
    storageBucket: 'flutter-test-8d68a.firebasestorage.app',
    measurementId: 'G-DL6W5E4J5W',
  );
}
